#Author: Vodohleb04
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(514, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(514, 164))
        Login.setMaximumSize(QtCore.QSize(514, 164))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../PPOIS_lab_4/gamedata/icons/bimer.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exitButton = QtWidgets.QPushButton(Login)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 5, 2, 1, 1)
        self.userEdit = QtWidgets.QLineEdit(Login)
        self.userEdit.setClearButtonEnabled(True)
        self.userEdit.setObjectName("userEdit")
        self.gridLayout.addWidget(self.userEdit, 0, 0, 1, 3)
        self.enterButton = QtWidgets.QPushButton(Login)
        self.enterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enterButton.setObjectName("enterButton")
        self.gridLayout.addWidget(self.enterButton, 5, 1, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(Login)
        self.passwordEdit.setInputMask("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 1, 0, 1, 3)
        self.registrationButton = QtWidgets.QPushButton(Login)
        self.registrationButton.setEnabled(False)
        self.registrationButton.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.registrationButton.setObjectName("registrationButton")
        self.gridLayout.addWidget(self.registrationButton, 5, 0, 1, 1)
        self.showPasswordButton = QtWidgets.QRadioButton(Login)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.gridLayout.addWidget(self.showPasswordButton, 4, 0, 1, 1)
        self.restorePasButton = QtWidgets.QPushButton(Login)
        self.restorePasButton.setEnabled(False)
        self.restorePasButton.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.restorePasButton.setObjectName("restorePasButton")
        self.gridLayout.addWidget(self.restorePasButton, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.exitButton.setText(_translate("Login", "Выйти"))
        self.userEdit.setPlaceholderText(_translate("Login", "Логин"))
        self.enterButton.setText(_translate("Login", "Войти"))
        self.passwordEdit.setPlaceholderText(_translate("Login", "Пароль"))
        self.registrationButton.setText(_translate("Login", "Регистрация"))
        self.showPasswordButton.setText(_translate("Login", "Видимый пароль"))
        self.restorePasButton.setText(_translate("Login", "Восстановить пароль"))

